### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by mrpwes** [Rendii09/RulesUI#1]
first join toggle at config.yml

**Comment by xxrbm** [comment]
Thank you! first join available please download v2.0.0

**Comment by xxrbm** [comment]
Thank you! first join is available please download [RulesUI v2.0.0](https://github.com/xxrbm/RulesUI/issues/1)

**Comment by xxrbm** [comment]
[RulesUI v2.0.0](https://github.com/xxrbm/RulesUI/releases/tag/v2.0.0)
